version: "3"
services:
  currency-exchange-service:
    image: currency-exchange-service:latest
    ports:
      - "5001:5001"
    networks:
      - opallios-microservice-net
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 64M

networks:
  opallios-microservice-net: